In [1]:
import torch
import spacy
import pandas as pd

<details>
<summary><strong>Dataset "wiki_bio_gpt3_hallucination</strong></summary>

https://huggingface.co/datasets/potsawee/wiki_bio_gpt3_hallucination
</details>


In [2]:
from datasets import load_dataset
dataset = load_dataset("potsawee/wiki_bio_gpt3_hallucination")

/work/nlx505/llm_hallucination/selfcheckgpt/selfcheck/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
dataset

DatasetDict({
    evaluation: Dataset({
        features: ['gpt3_text', 'wiki_bio_text', 'gpt3_sentences', 'annotation', 'wiki_bio_test_idx', 'gpt3_text_samples'],
        num_rows: 238
    })
})

In [22]:
dataset['evaluation'][0]

{'gpt3_text': "John Russell Reynolds (1820–1876) was an English lawyer, judge, and author. He was born in London, the son of a barrister, and was educated at Eton College and Trinity College, Cambridge. He was called to the bar in 1845, and became a Queen's Counsel in 1859. He was appointed a judge of the Court of Common Pleas in 1867, and was knighted in 1871.\n\nReynolds was a prolific author, writing on a wide range of topics. He wrote several books on legal topics, including The Law of Libel and Slander (1863), The Law of Copyright (1865), and The Law of Patents for Inventions (1868). He also wrote on a variety of other topics, including history, biography, and literature. He was a frequent contributor to the Saturday Review, and wrote several books on Shakespeare, including The Mystery of William Shakespeare (1848) and The Authorship of Shakespeare (1875). He also wrote a biography of the poet John Keats (1848).",
 'wiki_bio_text': 'Sir John Russell Reynolds, 1st Baronet (22 May 1

In [21]:
len(dataset['evaluation'][0]['gpt3_text_samples'])

20

In [4]:
df_dataset = pd.DataFrame(dataset['evaluation'])
df_dataset.head()

gpt3_text  \
0  John Russell Reynolds (1820–1876) was an Engli...   
1  Matthew Aylmer, 1st Baron Aylmer (1708–1794) w...   
2  Rick Mahler (born Richard Alan Mahler on April...   
3  James Blair (1732–1782) was an American lawyer...   
4  Tim Finchem (born August 24, 1947) is an Ameri...   

                                       wiki_bio_text  \
0  Sir John Russell Reynolds, 1st Baronet (22 May...   
1  Admiral of the Fleet Matthew Aylmer, 1st Baron...   
2  Richard Keith Mahler (August 5, 1953 in Austin...   
3  James Blair (September 26, 1786 - April 1, 183...   
4  Timothy W. Finchem (born April 19, 1947) is th...   

                                      gpt3_sentences  \
0  [John Russell Reynolds (1820–1876) was an Engl...   
1  [Matthew Aylmer, 1st Baron Aylmer (1708–1794) ...   
2  [Rick Mahler (born Richard Alan Mahler on Apri...   
3  [James Blair (1732–1782) was an American lawye...   
4  [Tim Finchem (born August 24, 1947) is an Amer...   

                                          annotation  wiki_bio_test_idx  \
0  [major_inaccurate, major_inaccurate, major_ina...              62464   
1  [minor_inaccurate, minor_inaccurate, minor_ina...              49661   
2  [minor_inaccurate, minor_inaccurate, accurate,...              20483   
3  [minor_inaccurate, major_inaccurate, major_ina...              71174   
4  [minor_inaccurate, accurate, major_inaccurate,...              39945   

                                   gpt3_text_samples  
0  [John Russell Reynolds (1 November 1829  – 11 ...  
1  ["Matthew Aylmer, 1st Baron Aylmer (c. 1650–17...  
2  [Rick Mahler (January 8, 1956 – May 25, 2005) ...  
3  [James Blair (April 2, 1755 – March 8, 1842) w...  
4  ["Tim Finchem (born May 27, 1953) is an Americ...

<details>
<summary><strong>Demo of the SelfCheckGPT scores</strong></summary>


</details>


In [5]:
torch.manual_seed(28)

In [6]:
nlp = spacy.load("en_core_web_sm")
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


In [66]:
# passage = """
# The Eiffel Tower is located in Paris and is made of chocolate. It is named after the engineer Gustave Eiffel.
# """.replace("\n", " ").strip()

passage = """
The Eiffel Tower is a symbol of French culture and ingenuity. It stands tall in the heart of Chantilly. Also it constructed primarily from wrought iron.
""".replace("\n", " ").strip()

In [67]:
# The Eiffel Tower is in Paris and made of iron. 
sample1 = """
The Eiffel Tower, recognized globally, dominates the Parisian skyline, crafted from over 7,000 metric tons of iron.
""".replace("\n", " ").strip()

# The Eiffel Tower is a famous landmark in France. Designed by Gustave Eiffel, it is named after him.
sample2 = """
The Eiffel Tower, an iconic structure, stands as a testament to France's architectural advancement, erroneously believed to be solely designed by Gustave Eiffel.
""".replace("\n", " ").strip()

# The Eiffel Tower was constructed in 188. Designed by Gustave Eiffel, it is named after him.
sample3 = """
Inaugurated in 1889 for the World's Fair, the Eiffel Tower's creation marked a pivotal moment in engineering history, despite Gustave Eiffel's initial reservations.
""".replace("\n", " ").strip()

In [6]:
dataset['evaluation'][4]

{'gpt3_text': 'Tim Finchem (born August 24, 1947) is an American businessman and former Commissioner of the PGA Tour. He served as Commissioner from 1994 to 2016.\n\nFinchem was born in Washington, D.C., and grew up in Bethesda, Maryland. He graduated from the University of Maryland in 1969 with a degree in business administration. He then attended the University of Virginia School of Law, where he earned his Juris Doctor degree in 1972.\n\nFinchem began his career in the golf industry in 1975, when he joined the PGA Tour as its first full-time legal counsel. He was promoted to Deputy Commissioner in 1988 and Commissioner in 1994. During his tenure, the PGA Tour grew from a domestic tour to an international tour, with events in more than 30 countries. He also oversaw the introduction of the FedEx Cup, a season-long points competition that culminates in a four-tournament playoff.\n\nFinchem retired as Commissioner in 2016 and was succeeded by Jay Monahan. He was inducted into the World 

In [9]:
passage = dataset['evaluation'][4]['gpt3_text']
sentences = dataset['evaluation'][4]['gpt3_sentences'][9:11]
samples = dataset['evaluation'][4]['gpt3_text_samples']
labels = dataset['evaluation'][4]['annotation'][9:11]

print(sentences)
print(labels)

['Finchem retired as Commissioner in 2016 and was succeeded by Jay Monahan.', 'He was inducted into the World Golf Hall of Fame in 2017.']
['accurate', 'major_inaccurate']


In [11]:
from selfcheckgpt.modeling_selfcheck import SelfCheckMQAG, SelfCheckBERTScore, SelfCheckNgram, SelfCheckNLI, SelfCheckLLMPrompt
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
nlp = spacy.load("en_core_web_sm")

selfcheck_mqag = SelfCheckMQAG(device=device) # set device to 'cuda' if GPU is available
selfcheck_bertscore = SelfCheckBERTScore(rescale_with_baseline=True)
selfcheck_ngram = SelfCheckNgram(n=1) # n=1 means Unigram, n=2 means Bigram, etc.
selfcheck_nli = SelfCheckNLI(device=device) # set device to 'cuda' if GPU is available

llm_model = "mistralai/Mistral-7B-Instruct-v0.2"
selfcheck_prompt = SelfCheckLLMPrompt(llm_model, device)

SelfCheck-MQAG initialized to device cpu
SelfCheck-BERTScore initialized
SelfCheck-1gram initialized
SelfCheck-NLI initialized to device cpu


Loading checkpoint shards: 100%|██████████| 3/3 [00:32<00:00, 10.81s/it]

SelfCheck-LLMPrompt (mistralai/Mistral-7B-Instruct-v0.2) initialized to device cpu


In [68]:
# LLM's text (e.g. GPT-3 response) to be evaluated at the sentence level  & Split it into sentences
sentences = [sent.text.strip() for sent in nlp(passage).sents] # spacy sentence tokenization
print(sentences)

# Other samples generated by the same LLM to perform self-check for consistency
# sample1 = "Michael Alan Weiner (born March 31, 1942) is an American radio host. He is the host of The Savage Country."
# sample2 = "Michael Alan Weiner (born January 13, 1960) is a Canadian radio host. He works at The New York Times."
# sample3 = "Michael Alan Weiner (born March 31, 1942) is an American radio host. He obtained his PhD from MIT."

['The Eiffel Tower is a symbol of French culture and ingenuity.', 'It stands tall in the heart of Chantilly.', 'Also it constructed primarily from wrought iron.']


In [9]:
from selfcheckgpt.modeling_mqag import MQAG

mqag_model = MQAG(
    g1_model_type='race', # race (more abstractive), squad (more extractive)
    device=device
)

questions = mqag_model.generate(context=sentences[0], do_sample=True, num_questions=2)
for i, question_item in enumerate(questions):
    print("------------------------------------")
    print(f"Q{i}: {question_item['question']}")
    print(f"A: {question_item['options'][0]}")
    print(f"B: {question_item['options'][1]}")
    print(f"C: {question_item['options'][2]}")
    print(f"D: {question_item['options'][3]}")

MQAG (race) initialized to cuda
Initialized Generation
------------------------------------
Q0: The Eiffel Tower is located in _.
A: Berlin
B: Paris
C: Edinburgh
D: Hong Kong
------------------------------------
Q1: The Eiffel Tower is a_.
A: tower
B: tower
C: building
D: building


In [12]:
question = questions[0]['question']
options = questions[0]['options']

print(question)
print(options)

questions = [{'question': question, 'options': options}]
probs = mqag_model.answer(questions=questions, context=sample1) # Answer based on sample1
print(probs[0])

The Eiffel Tower is located in _.
['Berlin', 'Paris', 'Edinburgh', 'Hong Kong']
[3.14628705e-05 9.99891877e-01 2.97255319e-05 4.69061924e-05]


In [69]:
samples = [sample1, sample2, sample3]

In [71]:
# --------------------------------------------------------------------------------------------------------------- #
# SelfCheck-MQAG: Score for each sentence where value is in [0.0, 1.0] and high value means non-factual
# Additional params for each scoring_method:
# -> counting: AT (answerability threshold, i.e. questions with answerability_score < AT are rejected)
# -> bayes: AT, beta1, beta2
# -> bayes_with_alpha: beta1, beta2
sent_scores_mqag = selfcheck_mqag.predict(
    sentences = sentences,               # list of sentences
    passage = passage,                   # passage (before sentence-split)
    # sampled_passages = [sample1, sample2, sample3], # list of sampled passages
    sampled_passages=samples[:15],
    num_questions_per_sent = 2,          # number of questions to be drawn  
    scoring_method = 'bayes_with_alpha', # options = 'counting', 'bayes', 'bayes_with_alpha'
    beta1 = 0.8, beta2 = 0.8,            # additional params depending on scoring_method
)
print(sent_scores_mqag)

[0.01842572 0.73710019 0.75946273]


In [72]:
# --------------------------------------------------------------------------------------------------------------- #
# SelfCheck-BERTScore: Score for each sentence where value is in [0.0, 1.0] and high value means non-factual
sent_scores_bertscore = selfcheck_bertscore.predict(
    sentences = sentences, # list of sentences
    sampled_passages = samples[:5], # list of sampled passages
)
print(sent_scores_bertscore)

[0.57331076 0.89748309 0.89230267]


In [73]:
# --------------------------------------------------------------------------------------------------------------- #
# SelfCheck-Ngram: Score at sentence- and document-level where value is in [0.0, +inf) and high value means non-factual
# as opposed to SelfCheck-MQAG and SelfCheck-BERTScore, SelfCheck-Ngram's score is not bounded
sent_scores_ngram = selfcheck_ngram.predict(
    sentences = sentences,   
    passage = passage,
    sampled_passages = samples[:5],
)
sent_scores_ngram
# {'sent_level': { # sentence-level score similar to MQAG and BERTScore variant
#     'avg_neg_logprob': [3.184312, 3.279774],
#     'max_neg_logprob': [3.476098, 4.574710]
#     },
#  'doc_level': {  # document-level score such that avg_neg_logprob is computed over all tokens
#     'avg_neg_logprob': 3.218678904916201,
#     'avg_max_neg_logprob': 4.025404834169327
#     }
# }

{'sent_level': {'avg_neg_logprob': [3.9134164989646103,
   3.859363439268631,
   4.18892870809842],
  'max_neg_logprob': [4.672828834461906,
   4.672828834461906,
   4.672828834461906]},
 'doc_level': {'avg_neg_logprob': 3.9726447795096687,
  'avg_max_neg_logprob': 4.672828834461906}}

In [74]:
sent_scores_nli = selfcheck_nli.predict(
    sentences = sentences, # list of sentences
    sampled_passages = samples[:5], # list of sampled passages
)
print(sent_scores_nli)

[0.05222131 0.990647   0.7649433 ]


In [75]:
sent_scores_prompt = selfcheck_prompt.predict(
    sentences = sentences,  # list of sentences
    sampled_passages = samples[:5], # list of sampled passages
    verbose = True, # whether to show a progress bar
)
print(sent_scores_prompt)

100%|██████████| 3/3 [01:00<00:00, 20.02s/it]

[0. 1. 0.]
